// <auto-generated />
using System;
using GitBackup.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitBackup.Data.Migrations
{
    [DbContext(typeof(GitBackupDbContext))]
    [Migration("20231009170507_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("GitBackup.Data.Models.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATE");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("REPOSITORY_ID");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("REPOSITORY_NAME");

                    b.HasKey("Id");

                    b.ToTable("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
